### ISSUE TITLE
Doesn't support key pair authentication

### ISSUE THREAD

**Issue by clhynfield** [pivotalservices/gtils#25]
The `gtils` package doesn't support SSH connections to hosts that only support key pair authentication, such as Pivotal Cloud Foundry AMIs on Amazon Web Services. This is needed to be able to back up PCF on AWS (see https://github.com/pivotalservices/cfbackup/issues/43).

**Comment by xchapter7x** [comment]
it is now possible to use ssh keys by setting the `SSLKey` element in the `SshConfig` 

this change is leveraged in the cfbackup lib and in the cfops binaries. 
latest cfops release will pull the sshkey from your ops manager installation settings file automatically and use it, if one exists.

closing this issue.

**Comment by skburgart** [comment]
This is still an issue in the latest master. Gtils only supports password-based authentication.
